### ISSUE TITLE
请问大佬用的是佳博哪个型号的打印机

### ISSUE THREAD

**Issue by andyy24** [yechaoa/PrinterDemo#1]
请问大佬用的是佳博哪个型号的打印机

**Comment by yechaoa** [comment]
GP-2120TU。
现在好像在官网上是找不到这款了，而且sdk不适配8.0，联系售后好几次了，说是适配之后联系我，emmmm，现在也没联系。不过7.0及以下还是可以用的。

**Comment by andyy24** [comment]
还有个问题，二维码打印sdk自带命令还是要自己生成图片发送给打印机打印？

**Comment by yechaoa** [comment]
传地址的话是可以生成二维码的，也可以自己生成二维码的图片然后打印图片

**Comment by andyy24** [comment]
先谢谢大佬，我还在用4.4，能否传一个佳博SDK包上来，官网什么都没有。

**Comment by yechaoa** [comment]
你把demo下载下来，按照README的步骤，在demo中copy就行了

**Comment by andyy24** [comment]
非常感谢，有遇到问题再请教！
