### ISSUE TITLE
提示连接成功，但是bt连接自动关闭，导致无法打印

### ISSUE THREAD

**Issue by andyy24** [yechaoa/PrinterDemo#2]
12-07 22:15:09.621 4489-4489/com.yechaoa.printertest I/main: onReceive(MainActivity.java:430)--->> STATE_CONNECTING
12-07 22:15:10.116 4489-4921/com.yechaoa.printertest D/BluetoothService: connected
    create ConnectedThread
12-07 22:15:10.116 4489-4922/com.yechaoa.printertest I/BluetoothService: BEGIN mConnectedThread
12-07 22:15:10.121 4489-4921/com.yechaoa.printertest D/GpPort: setState() 2 -> 3
    PrinterId() 0 -> 0
12-07 22:15:10.121 4489-4489/com.yechaoa.printertest I/GpPrintService: DeviceName: Printer_4DD9
    MESSAGE_STATE_CHANGE: 0
    STATE_CONNECTED
12-07 22:15:10.121 4489-4489/com.yechaoa.printertest I/GpDevice: retval = SUCCESS
12-07 22:15:10.121 4489-4489/com.yechaoa.printertest D/GpPrintUsb: send auth 1
12-07 22:15:10.131 4489-4489/com.yechaoa.printertest I/main: onReceive(MainActivity.java:441)--->> STATE_CONNECTED
12-07 22:15:14.121 4489-4489/com.yechaoa.printertest D/GpPrintUsb: send auth label 3
12-07 22:15:14.121 4489-4489/com.yechaoa.printertest D/GpPrintUsbPort: send ~!T
12-07 22:15:14.126 4489-4489/com.yechaoa.printertest I/GpDevice: retval = SUCCESS
12-07 22:15:18.126 4489-4489/com.yechaoa.printertest D/BluetoothService: stop
12-07 22:15:18.126 4489-4489/com.yechaoa.printertest D/GpPort: setState() 3 -> 0
    PrinterId() 0 -> 0
12-07 22:15:18.126 4489-4922/com.yechaoa.printertest D/GpPort: STATE NOT CHANGE
    connectionLost 
12-07 22:15:18.131 4489-4922/com.yechaoa.printertest W/System.err: java.io.IOException: bt socket closed, read return: -1
        at android.bluetooth.BluetoothSocket.read(BluetoothSocket.java:485)
        at android.bluetooth.BluetoothInputStream.read(BluetoothInputStream.java:96)
        at java.io.InputStream.read(InputStream.java:162)
        at com.gprinter.io.BluetoothPort$ConnectedThread.run(BluetoothPort.java:237)
12-07 22:15:18.131 4489-4922/com.yechaoa.printertest E/BluetoothService: disconnected
    java.io.IOException: bt socket closed, read return: -1
        at android.bluetooth.BluetoothSocket.read(BluetoothSocket.java:485)
        at android.bluetooth.BluetoothInputStream.read(BluetoothInputStream.java:96)
        at java.io.InputStream.read(InputStream.java:162)
        at com.gprinter.io.BluetoothPort$ConnectedThread.run(BluetoothPort.java:237)
12-07 22:15:18.131 4489-4922/com.yechaoa.printertest D/BluetoothService: Closing Bluetooth work
12-07 22:15:18.136 4489-4489/com.yechaoa.printertest I/GpPrintService: MESSAGE_STATE_CHANGE: 0
    STATE_NONE

**Comment by NatatkaValikowsky** [comment]
Hello! Did you solve this problem?

**Comment by yechaoa** [comment]
你重新关闭打开蓝牙试试

**Comment by andyy24** [comment]
> Hello! Did you solve this problem?

官网下载了官方sdk，里面有demo照着抄就ok了
