### ISSUE TITLE
I have a problem with app

### ISSUE THREAD

**Issue by NatatkaValikowsky** [yechaoa/PrinterDemo#3]
Hello! Help me please. The application finds the desired printer, shows the "Connection successful" window, however when I click the "Print" button it shows the waiting window and nothing else happens. No idea what this may be related to? Thank you for answer

**Comment by yechaoa** [comment]
I'm sorry for my late reply. This "gprintersdk" does have some problems.

First, it doesn't work on android 8.0 and above, and there's no official adaptation.
Secondly, this SDK is developed by "Gprinter" company, so it is for their printer.
You can see  http://www.gainscha.cn/

If neither, you can try

If it's IO, turn it off on ondestory.
Or restart the printer and bluetooth and reconnect.
Or print debugging.

**Comment by NatatkaValikowsky** [comment]
Thank you! I'll try to solve it and write here

**Comment by yechaoa** [comment]
good luck

**Comment by yechaoa** [comment]
@NatatkaValikowsky  A new version has been submitted
