### ISSUE TITLE
SDK2.2，未适配Android8.0以上系统

### ISSUE THREAD

**Issue by sunchengjian** [yechaoa/PrinterDemo#4]
这个SDK2.2，佳博官网没有适配Android8.0以上系统；但是我看到你那有个startservice（）然后在绑定bindService()；就在这个startservice（）的时候将 8.0以上系统分开处理如何？还有就是这个jar包内的GpPrinterService如何修改啊？适配 8.0

**Comment by yechaoa** [comment]
分不分开处理作用不大，主要是service里面的内容要适配，我也没仔细研究过，我已经放弃了...

**Comment by yechaoa** [comment]
@sunchengjian 新版本已经提交了
